markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6	
paginate_path: page/:num


# Build settings
# markdown: redcarpet
# redcarpet:
#     extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]

#SyntaxHihglighter config start

SyntaxHihglighter: false
shTheme: shThemeDefault # shThemeDefault  shThemeDjango  shThemeEclipse  shThemeEmacs  shThemeFadeToGrey  shThemeMidnight  shThemeRDark

#SyntaxHihglighter config end

#使用前阅读↓↓↓↓↓↓↓↓↓
#感谢您克隆此模板,但在使用前麻烦请把"<---"标记的更换成您的信息或删除(值留空白即可).非常感谢.
#使用前阅读↑↑↑↑↑↑↑↑↑
blog:
    name: dinglj                                          # 博客名称
    description: 蓝花楹咖啡屋                     # 博客描述
    title: dinglj                                         # 网页标题
    url: http://dinglj.github.io/                         # 博客地址
author:
    name: dinglj                                          # 作者名称
    email: 597063759@qq.com                                # 邮箱地址
    github: https://github.com/dinglj                     # GitHub地址
    logo: /res/img/my_head.jpg                              # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key